import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FoodCategoryProvider } from "./_provider/FoodCategory";
import { ToastProvider } from "./_components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Food-delivery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FoodCategoryProvider>{children}</FoodCategoryProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
